### ISSUE TITLE
lightbulb accessory hangs in Apples home app

### ISSUE THREAD

**Issue by Siri4Eden** [bendodson/homebridge-applescript-file-lightbulb#2]
In my iOS 10 Apple "home" app the lightbulb accessory hangs after successful initial "set iTunes volume to x %" (GUI and Siri) with an "exclamation mark" and "no response state". I am using your iTunes volume applescript. This leads to Siri stating "You don't seem to be playing anything right now" as - I guess - HomeKit disables the accessory due to the "no response" state.
Thanks for the great work and looking into this!

**Comment by luisfmoreira** [comment]
I'm having the same issue, but I modified your script to use kodi with json. Do you have any idea what it could be?

Kind regards

**Comment by bendodson** [comment]
If you set an action for the "on" and "off" states (not just "brightness") then the Home app on iOS 10 should work just fine. In my setup, I have:

"on" - script that sets iTunes volume to 100%
"off" - script that sets iTunes volume to 0%
"brightness" - script that sets iTunes volume to the value specified

If I leave on / off blank, then I get problems with the accessory hanging after the initial value is set correctly.

**Comment by Siri4Eden** [comment]
Brilliant, Thank you!
