### ISSUE TITLE
Homebridge running on my raspberry pi, can I ask it to play an AppleScript on my Mac?

### ISSUE THREAD

**Issue by thetom89** [bendodson/homebridge-applescript-file-lightbulb#3]
Hi Ben

Great Apple Script!  I have homebridge running on a raspberry pi though, do you know if there is anyway to use your method whereby the RPI talks to my MacBook Pro?

**Comment by bendodson** [comment]
It should be possible using some form of socket connection (i.e. the Pi connects directly to a server on the MacBook which then fires the AppleScript) but it isn't something I'm familiar with and would sidestep the need for this plugin in any case.
