### ISSUE TITLE
Sorry, X, I didn't hear back from your devices

### ISSUE THREAD

**Issue by CGDaveMac** [bendodson/homebridge-applescript-file-lightbulb#4]
Not sure if this is an issue with this code or a more general issue, but all the ON OFF scripts I have work, but any that use brightness, including the identical sample volume code work, but Siri comes back with the response "Sorry, X, I didn't hear back from your devices"

I read about the callback() setting... is that set properly?

**Comment by bendodson** [comment]
This has now been fixed.

The issue only occurred if you didn't provide an on and off script (as per my bad example) as the callback was never fired and thus it would hang. I had never noticed the problem as I was using an on and off script in addition to the volume control.

**Comment by CGDaveMac** [comment]
Perfect!!!

It works. For some reason NPM won’t update to 0.0.5 (propagation time?) but I made your changes to my files and it works perfectly.
