### ISSUE TITLE
Speaker support?

### ISSUE THREAD

**Issue by CGDaveMac** [bendodson/homebridge-applescript-file-lightbulb#5]
Any chance of updating or forking this for speaker support with iOS 11? I looked at the code, and it seems as simple as changing from lightbulbService to speakerService, but I haven't had the change to look at the APIs

**Comment by CGDaveMac** [comment]
One reason for this request is that speakers will work better with Siri requests for volume instead of using the brightness setting. Also, now that I think of it, it would be nice if switches could be used too.. I use this for some cool scripts that change settings on my receiver "Dolby Digital, Extended Stereo" and because they are all seen as light bulbs, if I say turn on the living room lights, these fake light bulb scripts turn on too. Switches would solve this, or putting these devices into a different zone in the Home app.

**Comment by bendodson** [comment]
Speakers don't currently work in iOS 11.2 so updating the plugin to support would likely just crash HomeKit from what I've read with others who have tried it. I expect iOS 11.3 to add support to coincide with the release of the HomePod.

This project won't be updated to support as it is a lightbulb version but I see no reason why I couldn't put together a new plugin for those that want to use a speaker instead.

There is already a simple switch version: https://github.com/bendodson/homebridge-applescript

**Comment by CGDaveMac** [comment]
Thanks for the update! I forgot that the speaker support isn't actually released yet.

**Comment by CGDaveMac** [comment]
Finally AirPlay 2 support! I hope you do indeed make a speaker version because AirPlay 2 devices are very limited right now!

**Comment by CGDaveMac** [comment]
Hi again! I was doing some work with my homebridge setup and found what looks like a HomeKit speaker setup here:
https://github.com/Supereg/homebridge-http-speaker <https://github.com/Supereg/homebridge-http-speaker>

I was going to see about figuring out the coding to adapt this with your applescript code, but I really have no idea what I am doing. Any chance you were still thinking about the new plugin?

I have been using your “lighbulbs" for speakers for awhile, the biggest downside is that when telling Siri to change a room’s actual lights, the speakers volume gets changed too.
